### ISSUE TITLE
为啥 new WxAccount 了还要判断是否为null？

### ISSUE THREAD

**Issue by chuntaojun** [champion97/wx-central#1]
`public WxMpService getMpService(String appId) {

        // TODO: 2019/3/21 可以从数据库查询公众号配置信息
        WxAccount wxAccount = new WxAccount();
        if (wxAccount == null) {
            logger.error("未找到对应appId=[%s]的配置信息", appId);
            throw new IllegalArgumentException(String.format("未找到对应appId=[%s]的配置信息", appId));
        }

        WxRedisConfigStorage wxRedisConfigStorage = new WxRedisConfigStorage(jedisPool);
        wxRedisConfigStorage.setAppId(wxAccount.getAppId());
        wxRedisConfigStorage.setSecret(wxAccount.getAppSecret());
        wxRedisConfigStorage.setToken(wxAccount.getToken());
        wxRedisConfigStorage.setAesKey(wxAccount.getEncodingAesKey());
        this.wxMpConfigStorage = wxRedisConfigStorage;

        return this;
    }`

为啥 new 了还要判断是否为null？

**Comment by champion97** [comment]
因为有个TODO
